export type Task = { id: string; title: string; detail?: string };
export type Recipe = Task & { required: boolean };
export type MachineGroup = { label: string; count: number; output: string; route?: string };
export type FactoryPlan = {
  id: string;
  site: string;
  name: string;
  item: string;
  recipe: string;
  machine: string;
  total: string;
  groups: MachineGroup[];
  note?: string;
  size?: string;
};
export type PhasePlan = {
  number: number;
  title: string;
  code: string;
  summary: string;
  duration: string;
  sites: string;
  doFirst: Task[];
  recipes: Recipe[];
  mam: Task[];
  utilities: Task[];
  factories: FactoryPlan[];
  gate: Task[];
};

const t = (id: string, title: string, detail?: string): Task => ({ id, title, detail });
const r = (id: string, title: string, required = true, detail?: string): Recipe => ({ id, title, required, detail });
const f = (
  id: string,
  site: string,
  item: string,
  machine: string,
  count: number,
  total: string,
  each: string,
  recipe = item,
  note?: string,
  size?: string,
): FactoryPlan => ({ id, site, name: id.toUpperCase(), item, machine, total, recipe, groups: [{ label: 'Shared output bank', count, output: each }], note, size });

const campusStandard: Task[] = [
  t('campus-datum', 'Set one world-grid datum for the campus.', 'Use a 4 m service plinth; do not drop production halls directly onto terrain.'),
  t('campus-alleys', 'Leave 8 m between neighboring buildings.', 'One clear foundation for walking, lifts, power and facade access.'),
  t('campus-boulevard', 'Reserve 24 m at freight and terminal edges.', 'Three foundations for a logistics boulevard; roads are optional access, not required routing.'),
  t('campus-truck-court', 'Reserve a 10 × 8 foundation truck court beside the terminal.', 'Keep it empty until Tier 3; it fits two stations plus a three-foundation turning/through lane.'),
  t('campus-services', 'Keep every belt and pipe gallery accessible.', 'Run services beneath or beside halls, never inside a sealed slab.'),
  t('campus-terraces', 'Use separate terraces when the terrain changes sharply.', 'Connect finished terraces with straight ramps or bridges.'),
];

const commonGate = (phase: number): Task[] => [
  t(`p${phase}-shells`, 'Every active hall has walls, roof, doors, lights and signs.'),
  t(`p${phase}-storage`, 'Terminal rows are the only storage; no machine-side buffers exist.'),
  t(`p${phase}-depots`, 'Every stored item has exactly one Depot uploader; ingots have none.'),
  t(`p${phase}-sink`, 'Every overflow path reaches the site Sink.'),
  t(`p${phase}-symmetry`, 'Machines sharing one output belt or pipe use equal output targets.'),
];

export const phases: PhasePlan[] = [
  {
    number: 0,
    title: 'Permanent Grid',
    code: 'WORLD DATUM',
    summary: 'Choose the Rocky Desert home campus and finish the permanent foundations, access and black-start power before production begins.',
    duration: 'Before Phase 1',
    sites: 'A · Rocky Desert basin',
    doFirst: [
      t('p0-settings', 'Start a fresh world with Default nodes and All Pure purity.'),
      t('p0-home', 'Move the HUB to the western flat basin at (-2633, -267).'),
      t('p0-base-building', 'Complete the Tier 1 Base Building milestone.', 'Foundations are mandatory before the permanent campus work begins.'),
      t('p0-plaza', 'Reserve a landscaped 15 × 15 Elevator plaza beside the HUB and MAM.'),
      ...campusStandard.map((x) => ({ ...x, id: `p0-${x.id}` })),
      t('p0-spine', 'Mark the north–south utility spine and terminal boulevard.'),
      t('p0-markers', 'Place map markers for A, B, B2, C and D.'),
    ],
    recipes: [r('p0-no-alt', 'No alternate recipes required', false, 'Save Hard Drive hunts for the Phase 1 checklist.')],
    mam: [
      t('p0-mam-built', 'Place the MAM in the permanent HUB plaza.'),
      t('p0-samples', 'Collect early samples: Caterium, Quartz, Sulfur, Mycelia, SAM, creature remains and slugs.'),
      t('p0-artifacts', 'Mark Mercer Spheres and Somersloops; do not spend them without updating the ledger.'),
    ],
    utilities: [
      t('p0-milestones', 'After Base Building, prioritize Logistics, Part Assembly, Obstacle Clearing, Sink Program and Logistics Mk.2.'),
      t('p0-shop', 'Buy concrete foundations, wall outlets, signs, lights, railings and conveyor holes before statues.'),
      t('p0-blueprint-datum', 'Prepare the 01-GRID-4X4 datum pattern by hand until Blueprints unlock.'),
    ],
    factories: [f('A-BLACK-START-P00', 'A', 'Black-start power', 'Biomass Burner', 16, '480 MW max', '30 MW', 'Biomass power', 'Automated Solid Biofuel delivery; manual Burner loading.', '12 × 8 foundations · 1 floor')],
    gate: [...commonGate(0), t('p0-gate-grid', 'The HUB, MAM, Elevator plaza and future halls all share the same datum.'), t('p0-gate-power', 'The black-start building can energize A without remote power.')],
  },
  {
    number: 1,
    title: 'Distribution Platform',
    code: 'PROJECT ASSEMBLY 1',
    summary: 'Build permanent starter halls at A, prove destination banks and deliver 50 Smart Plating without storing a single ingot.',
    duration: '25 min production',
    sites: 'A · Rocky Desert',
    doFirst: [
      t('p1-tier', 'Finish every Tier 0–2 milestone, including Sink Program and Logistics Mk.2.'),
      t('p1-corridor', 'Reserve the northbound utility corridor toward B.'),
      t('p1-terminal', 'Build the component terminal row, uploader bays and one shared Sink.'),
      ...campusStandard.slice(0, 3).map((x) => ({ ...x, id: `p1-${x.id}` })),
    ],
    recipes: [
      r('p1-iron-wire', 'Iron Wire', true, 'Mandatory; scan after Tier 2 Part Assembly.'),
      r('p1-stitched', 'Stitched Iron Plate', true),
      r('p1-cast-screws', 'Cast Screws', false, 'Optional convenience; the baseline uses default Screws.'),
    ],
    mam: [
      t('p1-mam-trees', 'Open every MAM tree with samples from the world.'),
      t('p1-caterium', 'Clear Caterium through AI Limiter and Smart Splitter.'),
      t('p1-quartz', 'Clear Quartz through Silica and Blade Runners.'),
      t('p1-organic', 'Clear currently affordable Nutrients, Alien Megafauna and Mycelia nodes.'),
      t('p1-slugs', 'Analyze one of each Power Slug and unlock overclocking.'),
      t('p1-alien', 'Analyze one Mercer Sphere and one Somersloop; advance Alien Technology as far as materials allow.'),
    ],
    utilities: [
      t('p1-shop', 'Buy the concrete/metal foundations, walls, outlets, conveyor holes, signs, lights and railings used at A.'),
      t('p1-solid-bio', 'Finish A-SOLID-BIOFUEL-C01 at 60/min.'),
      t('p1-organic-buildings', 'Finish small Fabric, Alien Protein and Alien DNA Capsule utility halls when their recipes unlock.'),
      t('p1-depot-bays', 'Complete labeled Depot bays even when Steel Pipe delays the uploader itself.'),
    ],
    factories: [
      { ...f('A-IRON-INGOT-S01', 'A', 'Iron Ingot', 'Smelter', 6, '170.556/min', 'varies', 'Iron Ingot', 'No storage or Depot.'), groups: [
        { label: 'Iron Plate bank', count: 2, output: '30/min each', route: '60/min → Plates' },
        { label: 'Iron Rod bank', count: 2, output: '27.5/min each', route: '55/min → Rods' },
        { label: 'Iron Wire bank', count: 2, output: '27.778/min each', route: '55.556/min → Wire' },
      ] },
      f('A-COPPER-INGOT-S01', 'A', 'Copper Ingot', 'Smelter', 2, '60/min', '30/min', 'Copper Ingot', 'Direct to Copper Sheets; no storage or Depot.'),
      f('A-COPPER-SHEET-C01', 'A', 'Copper Sheet', 'Constructor', 3, '30/min', '10/min'),
      f('A-CONCRETE-C01', 'A', 'Concrete', 'Constructor', 3, '40/min', '13.333/min'),
      { ...f('A-IRON-PLATE-C01', 'A', 'Iron Plate', 'Constructor', 3, '40/min', 'varies'), groups: [
        { label: 'RIP bank', count: 1, output: '16.667/min', route: '→ Reinforced Iron Plates' },
        { label: 'Terminal bank', count: 2, output: '11.667/min each', route: '→ Terminal' },
      ] },
      { ...f('A-IRON-ROD-C01', 'A', 'Iron Rod', 'Constructor', 4, '55/min', 'varies'), groups: [
        { label: 'Rotor bank', count: 1, output: '15/min', route: '→ Rotors' },
        { label: 'Screw bank', count: 2, output: '12.5/min each', route: '→ Screws' },
        { label: 'Terminal bank', count: 1, output: '15/min', route: '→ Terminal' },
      ] },
      { ...f('A-SCREW-C01', 'A', 'Screw', 'Constructor', 3, '100/min', 'varies', 'Screw'), groups: [
        { label: 'Rotor bank', count: 2, output: '37.5/min each', route: '75/min → Rotors' },
        { label: 'Terminal bank', count: 1, output: '25/min', route: '→ Terminal' },
      ] },
      { ...f('A-IRON-WIRE-C01', 'A', 'Wire', 'Constructor', 6, '100/min', 'varies', 'Iron Wire'), groups: [
        { label: 'Cable bank', count: 3, output: '20/min each', route: '60/min → Cable' },
        { label: 'RIP bank', count: 2, output: '16.667/min each', route: '33.333/min → RIP' },
        { label: 'Terminal bank', count: 1, output: '6.667/min', route: '→ Terminal' },
      ] },
      f('A-CABLE-C01', 'A', 'Cable', 'Constructor', 1, '30/min', '30/min'),
      { ...f('A-RIP-A01', 'A', 'Reinforced Iron Plate', 'Assembler', 2, '5/min', 'varies', 'Stitched Iron Plate'), groups: [
        { label: 'Smart Plating bank', count: 1, output: '2/min' },
        { label: 'Terminal bank', count: 1, output: '3/min' },
      ] },
      { ...f('A-ROTOR-A00', 'A', 'Rotor', 'Assembler', 2, '3/min', 'varies', 'Rotor', 'Legacy hall; switch off after Steel Rotor.'), groups: [
        { label: 'Smart Plating bank', count: 1, output: '2/min' },
        { label: 'Terminal bank', count: 1, output: '1/min' },
      ] },
      f('A-SMART-PLATING-A01', 'A', 'Smart Plating', 'Assembler', 1, '2/min', '2/min'),
      f('A-SOLID-BIOFUEL-C01', 'A', 'Solid Biofuel', 'Constructor', 1, '60/min', '60/min'),
    ],
    gate: [...commonGate(1), t('p1-50', '50 Smart Plating have reached the Elevator.'), t('p1-uploader-shells', 'Every component has its uploader or a finished technology-locked bay.'), t('p1-north', 'The route to B is marked and unobstructed.')],
  },
  {
    number: 2,
    title: 'Construction Dock',
    code: 'PROJECT ASSEMBLY 2',
    summary: 'Commission coal power, steel, the Concrete source campus and the Mk.1 blueprint book before the second delivery.',
    duration: '≤ 200 min production',
    sites: 'A · B · B2',
    doFirst: [
      t('p2-milestones', 'Unlock Coal Power → Basic Steel → Logistics Mk.3 → Advanced Steel → FICSIT Blueprints.'),
      t('p2-viaduct', 'Run a straight utility viaduct from A to B; bridge only difficult terrain.'),
      t('p2-concrete-shell', 'At B2, finish the 16-Constructor-capacity shell before running the first four machines.'),
      t('p2-circuits', 'Separate black-start, water/miners, generators and factories into priority circuits.'),
    ],
    recipes: [r('p2-solid-steel', 'Solid Steel Ingot'), r('p2-steel-rotor', 'Steel Rotor'), r('p2-steeled-frame', 'Steeled Frame'), r('p2-encased-pipe', 'Encased Industrial Pipe'), r('p2-copper-alloy', 'Copper Alloy Ingot', true, 'Bank for the later Dune Copper Works.')],
    mam: [
      t('p2-sulfur', 'Clear Sulfur through Black Powder, Compacted Coal, Expanded Toolbelt and Nobelisk Detonator.'),
      t('p2-mycelia', 'Clear Mycelia through Gas Mask and reachable inhalers; craft the Gas Mask.'),
      t('p2-caterium', 'Advance Caterium through AI Limiter, Smart Splitter and Power Switch.'),
      t('p2-quartz', 'Advance Quartz through Blade Runners, Crystal Oscillator and Inflated Pocket Dimension.'),
      t('p2-depots', 'Handcraft SAM Fluctuators and install all reserved Phase 1 uploaders; none on ingots.'),
      t('p2-rebar-research', 'Complete the Rebar Gun research branch; do not build a permanent Rebar factory.'),
    ],
    utilities: [
      t('p2-blueprints', 'Build and test the Mk.1 grid, terminal, bus, Constructor, Assembler, Foundry and Coal Generator blueprints.'),
      t('p2-black-powder', 'Finish A-BLACK-POWDER-A01.'),
      t('p2-nobelisk', 'Finish A-NOBELISK-A01 with terminal and Depot.'),
      t('p2-compacted', 'Finish B-COMPACTED-COAL-A01; keep the 12/min D bank off until Phase 3.'),
      t('p2-shop', 'Buy beams, pillars, catwalks, modern railings, road barriers and conveyor-wall pieces.'),
    ],
    factories: [
      f('B-COAL-POWER-P01', 'B', 'Coal power', 'Coal Generator', 16, '1,200 MW', '75 MW', 'Coal power', 'Two 8-generator halls; 8 Water Extractors at 90 m³/min each.', '22 × 16 foundations · 1 floor'),
      f('B-STEEL-INGOT-F01', 'B', 'Steel Ingot', 'Foundry', 5, '300/min', '60/min', 'Solid Steel Ingot', 'Storage-free dispatch throat.'),
      f('B2-CONCRETE-C01', 'B2', 'Concrete', 'Constructor', 4, '60/min', '15/min', 'Concrete', 'Build the shell for 16 Constructors now.', '18 × 6 foundations · 1 floor'),
      f('A-IRON-PLATE-C01', 'A', 'Iron Plate', 'Constructor', 3, '27.778/min', '9.259/min'),
      f('A-IRON-WIRE-C01', 'A', 'Wire', 'Constructor', 10, '205.556/min', '20.556/min', 'Iron Wire'),
      f('A-CABLE-C01', 'A', 'Cable', 'Constructor', 2, '50/min', '25/min'),
      f('A-RIP-A01', 'A', 'Reinforced Iron Plate', 'Assembler', 2, '8.333/min', '4.167/min', 'Stitched Iron Plate'),
      f('A-STEEL-PIPE-C01', 'A', 'Steel Pipe', 'Constructor', 2, '34.167/min', '17.083/min'),
      f('A-STEEL-BEAM-C01', 'A', 'Steel Beam', 'Constructor', 4, '60/min', '15/min'),
      f('A-ROTOR-A01', 'A', 'Rotor', 'Assembler', 1, '5/min', '5/min', 'Steel Rotor'),
      f('A-MOD-FRAME-A01', 'A', 'Modular Frame', 'Assembler', 2, '5/min', '2.5/min', 'Steeled Frame'),
      f('A-STATOR-A01', 'A', 'Stator', 'Assembler', 1, '2.5/min', '2.5/min'),
      f('A-SMART-PLATING-A01', 'A', 'Smart Plating', 'Assembler', 3, '5/min', '1.667/min'),
      f('A-VERSATILE-A01', 'A', 'Versatile Framework', 'Assembler', 2, '10/min', '5/min'),
      f('A-AUTO-WIRING-A01', 'A', 'Automated Wiring', 'Assembler', 1, '2.5/min', '2.5/min'),
      { ...f('B-COMPACTED-COAL-A01', 'B', 'Compacted Coal', 'Assembler', 2, '17/min', 'varies'), groups: [
        { label: 'D destination bank', count: 1, output: '12/min', route: '→ D in Phase 3' },
        { label: 'Terminal bank', count: 1, output: '5/min', route: 'Run until stocked' },
      ] },
    ],
    gate: [...commonGate(2), t('p2-blueprint-test', 'Two adjacent Mk.1 blueprints and one corner have been test-placed.'), t('p2-coal-stable', 'Coal plant has run 30 minutes without water cycling.'), t('p2-spare', 'Grid spare capacity is at least 25%.'), t('p2-gold-coast', 'The Gold Coast route is marked.')],
  },
  {
    number: 3,
    title: 'Main Body',
    code: 'PROJECT ASSEMBLY 3',
    summary: 'Open Oil, Quartz and Caterium campuses, establish manufacturer production and make Packaged Turbofuel your permanent Jetpack fuel.',
    duration: '250 min production',
    sites: 'A · B · C · D',
    doFirst: [
      t('p3-milestones', 'Prioritize Oil Processing, Logistics Mk.4, Industrial Manufacturing, Expanded Power and Blueprint Mk.2.'),
      t('p3-cave', 'Open the C cave portal near (-1880, -1415); bring filters, Nobelisks and lights.'),
      t('p3-gold', 'Establish D at the Pure Gold Coast oil field around (-2525, 698).'),
      t('p3-fluid-rule', 'Add labeled flush points; no crude, HOR or Fuel pipe may leave D.'),
    ],
    recipes: [r('p3-silicon-board', 'Silicon Circuit Board'), r('p3-cat-computer', 'Caterium Computer'), r('p3-heavy-frame', 'Heavy Encased Frame'), r('p3-silicon-hsc', 'Silicon High-Speed Connector', true, 'Bank for Phase 4.'), r('p3-insulated-osc', 'Insulated Crystal Oscillator', true, 'Bank for Phase 4.')],
    mam: [
      t('p3-mycelia', 'Clear Mycelia through Gas Filter and every reachable inhaler.'),
      t('p3-sulfur', 'Clear Sulfur through Turbofuel, Smokeless Powder, Rifle and Cluster Nobelisk.'),
      t('p3-weapons', 'Research Rebar and ammunition branches as available; build no Rifle/Rebar production halls.'),
      t('p3-caterium', 'Advance Caterium through Programmable Splitter.'),
      t('p3-quartz', 'Advance Quartz through Explorer, Pulse Nobelisk and Radar Technology.'),
    ],
    utilities: [
      t('p3-mk2-book', 'Build and test Mk.2 Manufacturer, Refinery, Blender, Fuel Generator, road, rail and Packager blueprints.'),
      t('p3-gas-filter', 'Finish A-GAS-FILTER-M01 at 7.5/min with terminal and Depot.'),
      t('p3-smokeless', 'Run D-SMOKELESS-R01 only for research and chosen Nobelisk variants.'),
      t('p3-fuel-first', 'Stock 50 Packaged Fuel for the Turbofuel MAM unlock.'),
      t('p3-turbo-final', 'Upgrade D-JETPACK-P01 to 15 Packaged Turbofuel/min.'),
      t('p3-shop', 'Buy oil/pipe cosmetics, windows, large doors and Mk.2 architecture pieces.'),
    ],
    factories: [
      f('C-SILICA-C01', 'C', 'Silica', 'Constructor', 8, '60/min', '7.5/min', 'Silica', 'Hall is sized for its Phase 4 peak.'),
      f('C-QUARTZ-CRYSTAL-C01', 'C', 'Quartz Crystal', 'Constructor', 2, '30/min', '15/min'),
      f('C-CATERIUM-INGOT-S01', 'C', 'Caterium Ingot', 'Smelter', 8, '15/min', '1.875/min', 'Caterium Ingot', 'No ingot storage.'),
      f('D-PLASTIC-R01', 'D', 'Plastic', 'Refinery', 6, '120/min', '20/min'),
      f('D-RUBBER-R01', 'D', 'Rubber', 'Refinery', 6, '120/min', '20/min'),
      f('D-EMERGENCY-FUEL-R01', 'D', 'Fuel', 'Refinery', 3, '120 m³/min', '40 m³/min', 'Residual Fuel'),
      f('D-EMERGENCY-POWER-P01', 'D', 'Fuel power', 'Fuel Generator', 6, '1,500 MW max', '250 MW', 'Fuel power', 'Run five while Jetpack fuel refills; sixth is switched reserve.', '17 × 7 foundations · 1 floor'),
      f('A-IRON-PLATE-C01', 'A', 'Iron Plate', 'Constructor', 3, '30.370/min', '10.123/min'),
      f('A-IRON-WIRE-C01', 'A', 'Wire', 'Constructor', 20, '436.741/min', '21.837/min', 'Iron Wire'),
      f('A-CABLE-C01', 'A', 'Cable', 'Constructor', 4, '100/min', '25/min'),
      f('A-RIP-A01', 'A', 'Reinforced Iron Plate', 'Assembler', 2, '9.111/min', '4.556/min', 'Stitched Iron Plate'),
      f('A-STEEL-PIPE-C01', 'A', 'Steel Pipe', 'Constructor', 7, '120.556/min', '17.222/min'),
      f('A-STEEL-BEAM-C01', 'A', 'Steel Beam', 'Constructor', 4, '60/min', '15/min'),
      f('A-MOD-FRAME-A01', 'A', 'Modular Frame', 'Assembler', 3, '7.667/min', '2.556/min', 'Steeled Frame'),
      f('A-EIB-A01', 'A', 'Encased Industrial Beam', 'Assembler', 1, '3.333/min', '3.333/min', 'Encased Industrial Pipe'),
      f('A-ROTOR-A01', 'A', 'Rotor', 'Assembler', 3, '12/min', '4/min', 'Steel Rotor'),
      f('A-STATOR-A01', 'A', 'Stator', 'Assembler', 3, '13/min', '4.333/min'),
      f('A-MOTOR-A01', 'A', 'Motor', 'Assembler', 1, '4/min', '4/min'),
      f('A-SMART-PLATING-A01', 'A', 'Smart Plating', 'Assembler', 2, '4/min', '2/min'),
      f('A-VERSATILE-A01', 'A', 'Versatile Framework', 'Assembler', 2, '10/min', '5/min'),
      f('A-AUTO-WIRING-A01', 'A', 'Automated Wiring', 'Assembler', 2, '5/min', '2.5/min'),
      f('A-COPPER-SHEET-C01', 'A', 'Copper Sheet', 'Constructor', 3, '28.6/min', '9.533/min'),
      f('A-CIRCUIT-BOARD-A01', 'A', 'Circuit Board', 'Assembler', 2, '13/min', '6.5/min', 'Silicon Circuit Board'),
      f('A-QUICKWIRE-C01', 'A', 'Quickwire', 'Constructor', 1, '28/min', '28/min'),
      f('A-COMPUTER-M01', 'A', 'Computer', 'Manufacturer', 1, '2/min', '2/min', 'Caterium Computer'),
      f('A-HMF-M01', 'A', 'Heavy Modular Frame', 'Manufacturer', 1, '1/min', '1/min', 'Heavy Encased Frame'),
      f('A-MOD-ENGINE-M01', 'A', 'Modular Engine', 'Manufacturer', 2, '2/min', '1/min'),
      f('A-ACU-M01', 'A', 'Adaptive Control Unit', 'Manufacturer', 1, '1/min', '1/min'),
      { ...f('D-EMPTY-CANISTER-C01', 'D', 'Empty Canister', 'Constructor', 2, '25/min initial', 'varies'), groups: [
        { label: 'Packager bank', count: 1, output: '20/min → 15/min' },
        { label: 'Terminal fill bank', count: 1, output: '5/min', route: 'Switch off when stocked' },
      ] },
      f('D-JETPACK-P01', 'D', 'Packaged Turbofuel', 'Packager', 1, '15/min final', '15/min', 'Packaged Turbofuel', 'First run 20 Packaged Fuel/min; then retarget once.'),
      f('D-TURBOFUEL-R01', 'D', 'Turbofuel', 'Refinery', 1, '15 m³/min', '15 m³/min'),
      f('A-GAS-FILTER-M01', 'A', 'Gas Filter', 'Manufacturer', 1, '7.5/min', '7.5/min'),
      f('D-SMOKELESS-R01', 'D', 'Smokeless Powder', 'Refinery', 1, '20/min batch', '20/min'),
    ],
    gate: [...commonGate(3), t('p3-no-fluid', 'No fluid leaves D; every pipe is labeled and has a flush point.'), t('p3-turbofuel', 'Packaged Turbofuel is available through D’s sole Depot.'), t('p3-mk2-test', 'Mk.2 production and transport blueprints have been test-placed.'), t('p3-spare', 'Grid has at least 25% spare power.'), t('p3-routes', 'Routes to E, F and G are surveyed.')],
  },
  {
    number: 4,
    title: 'Propulsion',
    code: 'PROJECT ASSEMBLY 4',
    summary: 'Turn the world into a finished network: Aluminum, Nitrogen, Rocket Fuel power, Dune Copper and four dedicated Project Assembly halls.',
    duration: '250 min production',
    sites: 'A · B · B2 · C · D · E · F · G · H',
    doFirst: [
      t('p4-source-first', 'Finish source campuses E, F, G and H before the four Project Part halls.'),
      t('p4-d-upgrade', 'Upgrade D to six Diluted Fuel Blenders and 27 Fuel Generators.'),
      t('p4-e-water', 'Build E’s recycled-water loop with fresh water after the priority return.'),
      t('p4-g-districts', 'Build two mirrored 9 GW Nitro Rocket Fuel districts at G.'),
      t('p4-storage', 'Finish and charge at least 50 Power Storages.'),
      t('p4-h-stage1', 'Build H stage 1 with 12 Copper Alloy Foundries and two storage-free dispatch lanes.'),
    ],
    recipes: [r('p4-sloppy', 'Sloppy Alumina'), r('p4-pure-al', 'Pure Aluminum Ingot'), r('p4-heat', 'Heat Exchanger'), r('p4-cooling', 'Cooling Device'), r('p4-hor', 'Heavy Oil Residue'), r('p4-diluted', 'Diluted Fuel'), r('p4-nitro', 'Nitro Rocket Fuel', true, 'Finish Sulfur MAM through Rocket Fuel before scanning.'), r('p4-hsc', 'Silicon High-Speed Connector'), r('p4-osc', 'Insulated Crystal Oscillator')],
    mam: [
      t('p4-sulfur', 'Finish Sulfur through Rocket Fuel before the Nitro Rocket Fuel scan.'),
      t('p4-caterium', 'Complete Caterium through Priority Power Switch and Programmable Splitter.'),
      t('p4-quartz', 'Complete Quartz through Radar Technology and Priority Merger.'),
      t('p4-all-trees', 'Clear every remaining non-Tier-9 Nutrients, Mycelia, Alien Megafauna and Power Slug node.'),
      t('p4-turbo-ammo-research', 'Handcraft 1,000 Rifle Ammo only for Turbo Rifle Ammo research; submit 50 Packaged Turbofuel and 100 Casings.'),
      t('p4-nuclear-deterrent', 'Submit 10 Encased Uranium Cells, 500 Nobelisks and 100 AI Limiters for Nuclear Deterrent.'),
    ],
    utilities: [
      t('p4-iodine', 'Finish one Iodine-Infused Filter Manufacturer.'),
      t('p4-uranium-annex', 'At E, finish the Sulfuric Acid Refinery and Encased Uranium Cell Blender research annexes; make exactly 10 cells.'),
      t('p4-no-ammo', 'Build no Turbo Rifle Ammo, Packaged Rocket Fuel or specialty-rebar halls.'),
      t('p4-shop', 'Buy rail platforms, road markings, frame foundations, lights and final E/F/G/H facade pieces.'),
      t('p4-reserves', 'Maintain terminal reserves: 20 Plate, 60 Wire, 30 Cable, 20 Pipe, 15 Beam and 30 Concrete/min.'),
    ],
    factories: [
      f('D-DILUTED-FUEL-B01', 'D', 'Fuel', 'Blender', 6, '540 m³/min', '90 m³/min', 'Diluted Fuel'),
      f('D-FUEL-GEN-P02', 'D', 'Fuel power', 'Fuel Generator', 27, '6,750 MW', '250 MW', 'Fuel power', 'Switch one off while Turbofuel refills.', '37 × 12 foundations · 1 floor'),
      f('E-ALUMINA-R01', 'E', 'Alumina Solution', 'Refinery', 2, '330 m³/min', '165 m³/min', 'Sloppy Alumina'),
      f('E-AL-SCRAP-R01', 'E', 'Aluminum Scrap', 'Refinery', 2, '495/min', '247.5/min'),
      f('E-AL-INGOT-S01', 'E', 'Aluminum Ingot', 'Smelter', 9, '247.5/min', '27.5/min', 'Pure Aluminum Ingot', 'No storage or Depot.'),
      f('E-AL-CASING-C01', 'E', 'Aluminum Casing', 'Constructor', 3, '165/min', '55/min'),
      f('E-ALCLAD-A01', 'E', 'Alclad Aluminum Sheet', 'Assembler', 1, '30/min reserve', '30/min'),
      f('F-FUSED-FRAME-B01', 'F', 'Fused Modular Frame', 'Blender', 1, '1.5/min', '1.5/min'),
      f('F-COOLING-B01', 'F', 'Cooling System', 'Blender', 2, '7/min', '3.5/min', 'Cooling Device'),
      f('G-NITRO-POWER-P01', 'G', 'Rocket Fuel power', 'Fuel Generator', 72, '18,000 MW', '250 MW', 'Nitro Rocket Fuel', 'Two independently switched 36-generator districts.', '47 × 22 foundations · 1 floor'),
      f('H-COPPER-INGOT-F01', 'H', 'Copper Ingot', 'Foundry', 12, '1,200/min', '100/min', 'Copper Alloy Ingot', 'Two Mk.5 storage-free lanes.'),
      f('H-COPPER-POWDER-C01', 'H', 'Copper Powder', 'Constructor', 2, '100/min', '50/min'),
      f('A-IRON-INGOT-S01', 'A', 'Iron Ingot', 'Smelter', 52, '1,544.795/min', '29.708/min', 'Iron Ingot', 'Three separate miner feeds; no storage.'),
      f('B-STEEL-INGOT-F01', 'B', 'Steel Ingot', 'Foundry', 14, '820.833/min', '58.631/min', 'Solid Steel Ingot', 'Two equal-rate Mk.5 dispatch banks.'),
      f('B2-CONCRETE-C01', 'B2', 'Concrete', 'Constructor', 12, '180/min', '15/min'),
      f('C-SILICA-C01', 'C', 'Silica', 'Constructor', 10, '300/min', '30/min'),
      f('A-IRON-PLATE-C01', 'A', 'Iron Plate', 'Constructor', 4, '74.815/min', '18.704/min'),
      f('A-IRON-WIRE-C01', 'A', 'Wire', 'Constructor', 71, '1,593.630/min', '22.446/min', 'Iron Wire'),
      f('A-CABLE-C01', 'A', 'Cable', 'Constructor', 15, '430/min', '28.667/min'),
      f('A-STEEL-PIPE-C01', 'A', 'Steel Pipe', 'Constructor', 23, '457.222/min', '19.879/min'),
      f('A-STEEL-BEAM-C01', 'A', 'Steel Beam', 'Constructor', 3, '45/min', '15/min'),
      f('A-COPPER-SHEET-C01', 'A', 'Copper Sheet', 'Constructor', 27, '261.9/min', '9.7/min'),
      f('A-QUICKWIRE-C01', 'A', 'Quickwire', 'Constructor', 10, '596/min', '59.6/min'),
      f('A-RIP-A01', 'A', 'Reinforced Iron Plate', 'Assembler', 3, '16.444/min', '5.481/min', 'Stitched Iron Plate'),
      f('A-MOD-FRAME-A01', 'A', 'Modular Frame', 'Assembler', 6, '17.167/min', '2.861/min', 'Steeled Frame'),
      f('A-EIB-A01', 'A', 'Encased Industrial Beam', 'Assembler', 5, '18.333/min', '3.667/min', 'Encased Industrial Pipe'),
      f('A-ROTOR-A01', 'A', 'Rotor', 'Assembler', 6, '30/min', '5/min', 'Steel Rotor'),
      f('A-STATOR-A01', 'A', 'Stator', 'Assembler', 10, '48/min', '4.8/min'),
      f('A-MOTOR-A01', 'A', 'Motor', 'Assembler', 3, '12.5/min', '4.167/min'),
      f('A-CIRCUIT-BOARD-A01', 'A', 'Circuit Board', 'Assembler', 9, '102/min', '11.333/min', 'Silicon Circuit Board'),
      f('A-COMPUTER-M01', 'A', 'Computer', 'Manufacturer', 6, '19/min', '3.167/min', 'Caterium Computer'),
      f('A-HMF-M01', 'A', 'Heavy Modular Frame', 'Manufacturer', 2, '5.5/min', '2.75/min', 'Heavy Encased Frame'),
      f('A-SUPERCOMPUTER-M01', 'A', 'Supercomputer', 'Manufacturer', 2, '2/min', '1/min'),
      f('A-HSC-M01', 'A', 'High-Speed Connector', 'Manufacturer', 2, '6/min', '3/min', 'Silicon High-Speed Connector'),
      f('A-OSCILLATOR-M01', 'A', 'Crystal Oscillator', 'Manufacturer', 1, '1.5/min', '1.5/min', 'Insulated Crystal Oscillator'),
      f('A-RCU-M01', 'A', 'Radio Control Unit', 'Manufacturer', 2, '3/min', '1.5/min'),
      f('A-MOD-ENGINE-M01', 'A', 'Modular Engine', 'Manufacturer', 3, '2.5/min', '0.833/min'),
      f('A-ACU-M01', 'A', 'Adaptive Control Unit', 'Manufacturer', 4, '4/min', '1/min'),
      f('A-TURBO-MOTOR-M01', 'A', 'Turbo Motor', 'Manufacturer', 1, '1/min', '1/min'),
      f('A-ADS-A01', 'A', 'Assembly Director System', 'Assembler', 3, '2/min', '0.667/min'),
      f('A-MFG-A01', 'A', 'Magnetic Field Generator', 'Assembler', 2, '2/min', '1/min'),
      f('A-TPR-M01', 'A', 'Thermal Propulsion Rocket', 'Manufacturer', 1, '1/min', '1/min'),
      f('A-NUCLEAR-PASTA-PA01', 'A', 'Nuclear Pasta', 'Particle Accelerator', 1, '0.5/min', '0.5/min'),
      f('E-SULFURIC-ACID-R01', 'E', 'Sulfuric Acid', 'Refinery', 1, 'research batch', 'as required'),
      f('E-ENC-URANIUM-B01', 'E', 'Encased Uranium Cell', 'Blender', 1, '10 total', '25/min while active'),
    ],
    gate: [...commonGate(4), t('p4-water-loop', 'E’s recycled-water loop survives a cold restart.'), t('p4-nitrogen', 'No Nitrogen pipe leaves F.'), t('p4-g-independent', 'Both 9 GW G districts run independently; 50 Power Storages are charged.'), t('p4-belts', 'No Mk.5 belt exceeds 780/min.'), t('p4-research', 'Every non-Tier-9 MAM node is complete, including weapon and Nuclear Deterrent research.')],
  },
  {
    number: 5,
    title: 'Assembly',
    code: 'SAVE THE DAY',
    summary: 'Expand Copper and power, commission the Quantum campus, retarget the completed halls and run the final four parts to completion.',
    duration: '500 min pacing run',
    sites: 'A · B · B2 · C · D · E · F · G · H · Q',
    doFirst: [
      t('p5-tier9', 'Unlock Matter Conversion → Quantum Encoding → Peak Efficiency → Blueprint Mk.3.'),
      t('p5-g-expand', 'Expand G to four Nitro lines: 144 generators / 36 GW.'),
      t('p5-storage', 'Charge at least 100 Power Storages.'),
      t('p5-h-expand', 'Expand H to 36 Copper Alloy Foundries and three Mk.6 dispatch lanes.'),
      t('p5-q-layout', 'At Q (-1436, 207), place low black/violet halls around a white-lit courtyard.'),
      t('p5-priority', 'Give Particle Accelerators, Encoders, Converters and portals separate priority groups.'),
    ],
    recipes: [r('p5-pink', 'Pink Diamonds', true, 'The only new plan-critical alternate in Phase 5.')],
    mam: [
      t('p5-alien', 'Clear every newly reachable Alien Technology node.'),
      t('p5-shards', 'Clear Synthetic Power Shards; use a separate Encoder building if automated.'),
      t('p5-slugs', 'Clear every remaining Power Slug node.'),
      t('p5-audit', 'Audit the MAM for zero unfinished nonseasonal nodes, including all weapon branches.'),
      t('p5-shop', 'Clear all remaining nonseasonal functional AWESOME Shop unlocks; statues are now allowed.'),
    ],
    utilities: [
      t('p5-sam-stock', 'Refill Q-SAM-FLUCT-M01, then switch it off before the 500-minute run.'),
      t('p5-artifact-audit', 'Audit every Depot uploader and installed Somersloop; ingots have neither.'),
      t('p5-xbox', 'Commission G in 36-generator blocks and check Xbox performance after each block.'),
      t('p5-console-option', 'If needed, use 72 generators at 500 MW each after Synthetic Shards; otherwise keep 144 ordinary generators.'),
      t('p5-unslooped', 'Run the documented core once without production amplification.'),
    ],
    factories: [
      f('H-COPPER-INGOT-F01', 'H', 'Copper Ingot', 'Foundry', 36, '3,600/min', '100/min', 'Copper Alloy Ingot', 'Three Mk.6 storage-free lanes.'),
      f('H-COPPER-POWDER-C01', 'H', 'Copper Powder', 'Constructor', 10, '500/min', '50/min'),
      { ...f('C-QUARTZ-CRYSTAL-C01', 'C', 'Quartz Crystal', 'Constructor', 14, '299/min', 'varies'), groups: [
        { label: 'H bank', count: 11, output: '21.273/min each', route: '234/min → Diamonds' },
        { label: 'Q bank', count: 3, output: '21.667/min each', route: '65/min → Q' },
      ] },
      { ...f('H-PINK-DIAMOND-V01', 'H', 'Diamonds', 'Converter', 6, '78/min', 'varies', 'Pink Diamonds'), groups: [
        { label: 'Dark Matter Crystal bank', count: 5, output: '13.6/min each', route: '68/min → Q' },
        { label: 'Time Crystal bank', count: 1, output: '10/min', route: '→ Q' },
      ] },
      f('A-IRON-INGOT-S01', 'A', 'Iron Ingot', 'Smelter', 48, '1,440/min', '30/min', 'Iron Ingot', 'Two Mk.6 lanes; no storage.'),
      f('B-STEEL-INGOT-F01', 'B', 'Steel Ingot', 'Foundry', 10, '600/min', '60/min', 'Solid Steel Ingot'),
      f('B2-CONCRETE-C01', 'B2', 'Concrete', 'Constructor', 16, '240/min', '15/min'),
      f('C-SILICA-C01', 'C', 'Silica', 'Constructor', 8, '240/min', '30/min'),
      f('E-ALUMINA-R01', 'E', 'Alumina Solution', 'Refinery', 3, '694 m³/min', '231.333 m³/min', 'Sloppy Alumina'),
      f('E-AL-SCRAP-R01', 'E', 'Aluminum Scrap', 'Refinery', 3, '1,041/min', '347/min'),
      f('E-AL-INGOT-S01', 'E', 'Aluminum Ingot', 'Smelter', 18, '520.5/min', '28.917/min', 'Pure Aluminum Ingot', 'No storage or Depot.'),
      f('E-AL-CASING-C01', 'E', 'Aluminum Casing', 'Constructor', 6, '329/min', '54.833/min'),
      f('G-NITRO-POWER-P02', 'G', 'Rocket Fuel power', 'Fuel Generator', 144, '36,000 MW', '250 MW', 'Nitro Rocket Fuel', 'Four independently switched lines.', '47 × 42 foundations · 1 floor'),
      { ...f('Q-REANIMATED-SAM-C01', 'Q', 'Reanimated SAM', 'Constructor', 7, '180.833/min', 'varies'), groups: [
        { label: 'Ficsite bank', count: 3, output: '24.444/min each', route: '73.333/min → Ficsite' },
        { label: 'Fresh DMR bank', count: 4, output: '26.875/min each', route: '107.5/min → DMR' },
      ] },
      f('Q-FICSITE-INGOT-V01', 'Q', 'Ficsite Ingot', 'Converter', 2, '18.333/min', '9.167/min', 'Ficsite Ingot (Iron)', 'Direct to Trigons; no storage.'),
      { ...f('Q-FICSITE-TRIGON-C01', 'Q', 'Ficsite Trigon', 'Constructor', 3, '55/min', 'varies'), groups: [
        { label: 'NQP bank', count: 1, output: '15/min' },
        { label: 'Biochemical bank', count: 2, output: '20/min each' },
      ] },
      f('Q-EPM-V01', 'Q', 'Excited Photonic Matter', 'Converter', 1, '125 m³/min', '125 m³/min'),
      f('Q-DMR-V01', 'Q', 'Dark Matter Residue', 'Converter', 3, '215 m³/min', '71.667 m³/min'),
      f('Q-TIME-CRYSTAL-V01', 'Q', 'Time Crystal', 'Converter', 1, '5/min', '5/min'),
      { ...f('Q-DARK-MATTER-PA01', 'Q', 'Dark Matter Crystal', 'Particle Accelerator', 4, '68/min', 'varies'), groups: [
        { label: 'Superposition bank', count: 1, output: '18/min' },
        { label: 'Singularity bank', count: 1, output: '10/min' },
        { label: 'Warp Drive bank', count: 2, output: '20/min each' },
      ] },
      f('Q-SUPERPOSITION-QE01', 'Q', 'Superposition Oscillator', 'Quantum Encoder', 1, '3/min', '3/min'),
      f('Q-NEURAL-QE01', 'Q', 'Neural-Quantum Processor', 'Quantum Encoder', 1, '1/min', '1/min'),
      f('Q-AI-SERVER-QE01', 'Q', 'AI Expansion Server', 'Quantum Encoder', 1, '1/min', '1/min'),
      f('Q-BIOCHEM-B01', 'Q', 'Biochemical Sculptor', 'Blender', 1, '2/min', '2/min'),
      f('Q-SAM-FLUCT-M01', 'Q', 'SAM Fluctuator', 'Manufacturer', 1, '5/min utility', '5/min', 'SAM Fluctuator', 'Switch off before the launch run.'),
      f('A-IRON-PLATE-C01', 'A', 'Iron Plate', 'Constructor', 5, '96.111/min', '19.222/min'),
      f('A-IRON-WIRE-C01', 'A', 'Wire', 'Constructor', 33, '724.222/min', '21.946/min', 'Iron Wire'),
      f('A-CABLE-C01', 'A', 'Cable', 'Constructor', 4, '100/min', '25/min'),
      f('A-STEEL-PIPE-C01', 'A', 'Steel Pipe', 'Constructor', 18, '342.667/min', '19.037/min'),
      f('A-COPPER-SHEET-C01', 'A', 'Copper Sheet', 'Constructor', 21, '205.4/min', '9.781/min'),
      f('A-QUICKWIRE-C01', 'A', 'Quickwire', 'Constructor', 10, '555/min', '55.5/min'),
      f('A-CIRCUIT-BOARD-A01', 'A', 'Circuit Board', 'Assembler', 6, '69.5/min', '11.583/min', 'Silicon Circuit Board'),
      f('A-COMPUTER-M01', 'A', 'Computer', 'Manufacturer', 4, '15/min', '3.75/min', 'Caterium Computer'),
      f('A-HMF-M01', 'A', 'Heavy Modular Frame', 'Manufacturer', 2, '4.5/min', '2.25/min', 'Heavy Encased Frame'),
      f('A-OSCILLATOR-M01', 'A', 'Crystal Oscillator', 'Manufacturer', 4, '6.5/min', '1.625/min', 'Insulated Crystal Oscillator'),
      f('A-RCU-M01', 'A', 'Radio Control Unit', 'Manufacturer', 3, '7/min', '2.333/min'),
      f('A-SINGULARITY-M01', 'A', 'Singularity Cell', 'Manufacturer', 1, '5/min', '5/min'),
      f('A-NUCLEAR-PASTA-PA01', 'A', 'Nuclear Pasta', 'Particle Accelerator', 5, '2.5/min total', '0.5/min', 'Nuclear Pasta', '2/min delivered + 0.5/min internal.'),
      f('A-BIOCHEM-B01', 'A', 'Biochemical Sculptor', 'Blender', 1, '2/min', '2/min'),
      f('A-AI-SERVER-QE01', 'A', 'AI Expansion Server', 'Quantum Encoder', 1, '1/min', '1/min'),
      f('A-WARP-DRIVE-M01', 'A', 'Ballistic Warp Drive', 'Manufacturer', 1, '1/min', '1/min'),
    ],
    gate: [...commonGate(5), t('p5-commodities', 'All seven commodity lanes arrive; three ingots are storage-free.'), t('p5-fluids', 'No fluid crosses D, E, F, G or Q boundaries.'), t('p5-power-restart', 'Every remote site survives a controlled power restart.'), t('p5-project', 'Final delivery: 1,000 Nuclear Pasta, 1,000 Biochemical Sculptors, 256 AI Servers and 200 Warp Drives.'), t('p5-walk', 'Take one final walk through the completed world before launching.')],
  },
];

export const allTaskIds = phases.flatMap((phase) => [
  ...phase.doFirst.map((x) => x.id),
  ...phase.recipes.map((x) => x.id),
  ...phase.mam.map((x) => x.id),
  ...phase.utilities.map((x) => x.id),
  ...phase.gate.map((x) => x.id),
  ...phase.factories.flatMap((factory) => [
    `${factory.id}-shell`,
    `${factory.id}-terminal`,
    ...factory.groups.flatMap((group, groupIndex) => Array.from({ length: group.count }, (_, machineIndex) => `${factory.id}-g${groupIndex}-m${machineIndex}`)),
  ]),
]);
